trigger:
- main

variables:
  azureSubscription: '8935920_service_connection'  
  functionAppName: '8935920'                       
  resourceGroup: '8935920_function'             
  pythonVersion: '3.9'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        zip -r functionapp.zip .
      displayName: 'Build Python package'

    - publish: 'functionapp.zip'
      artifact: drop

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: drop

    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(azureSubscription)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Setting WEBSITE_RUN_FROM_PACKAGE=1"
          az functionapp config appsettings set \
            --name $(functionAppName) \
            --resource-group $(resourceGroup) \
            --settings WEBSITE_RUN_FROM_PACKAGE=1

          echo "Deploying package using az functionapp deployment source config-zip"
          az functionapp deployment source config-zip \
            --name $(functionAppName) \
            --resource-group $(resourceGroup) \
            --src "$(Pipeline.Workspace)/drop/functionapp.zip"
