trigger:
- main

variables:
  azureSubscription: '8935920_service_connection'  
  functionAppName: '8935920'                      
  pythonVersion: '3.9'

stages:
- stage: Build
  jobs:
  - job: Build
    pool: 
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs: 
        versionSpec: '$(pythonVersion)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        zip -r functionapp.zip .
      displayName: 'Build Python package'

    - publish: 'functionapp.zip'
      artifact: drop

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: Deploy
    pool: 
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: drop

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: '$(azureSubscription)'
        appType: 'functionAppLinux'
        appName: '$(functionAppName)'
        package: '$(Pipeline.Workspace)/drop/functionapp.zip'
        deploymentMethod: 'runFromPackage'
